DjangoApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
# from restaurants.views import HomeView

from django.contrib.auth.views import LoginView


# from restaurants.views import (
#     restaurant_createview,
#     restaurant_listview,
#     RestaurantListView,
#     RestaurantDetailView,
#     RestaurantCreateView
# )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name="home.html"), name='home'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    #url(r'^restaurants/$', RestaurantListView.as_view(), name='restaurants'),
    # url(r'^restaurants/create/$', restaurant_createview),
    #url(r'^restaurants/create/$', RestaurantCreateView.as_view(), name='restaurants-create'),
    #url(r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name='restaurant-detail'),
    # url(r'^restaurants/(?P<slug>\w+)/$', RestaurantListView.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name='contact'),
]

menus/urls.py
from django.conf.urls import url, include


from django.contrib.auth.views import LoginView


from .views import (
    ItemListView,
    ItemCreateView,
    ItemDetailView,
    ItemUpdateView
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
]

templates/snippets/css.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

templates/snippets/form-snippet.html
{% if errors.non_field_errors %}
    {{ form.errors.non_field_errors }}
{% endif %}

{#    csrf_token gets the data from the form#}
<form method="post"> {% csrf_token %}
{#        Django default form#}
    {{  form.as_p }}
    <button type="submit">Save</button>
</form>

templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class="container">
    <h1>Welcome to my korean Restaurant</h1>
    <a href="{% url "home" %}">Home</a>
    <a href="{% url "about" %}">About</a>
    <a href="{% url "contact" %}">Contact</a>
    {% if request.user.is_authenticated %}
    <a href="{% url "restaurants:list" %}">Restaurants</a>
    <a href="{% url "menus:list" %}">Menu Items</a>
    {% endif %}

{#    Find the name of e.g. home in the url.py name='home'#}
</div>

templates/snippets/sidebar.html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
</ul>