DjangoApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
# from restaurants.views import HomeView

from django.contrib.auth.views import LoginView


# from restaurants.views import (
#     restaurant_createview,
#     restaurant_listview,
#     RestaurantListView,
#     RestaurantDetailView,
#     RestaurantCreateView
# )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name="home.html"), name='home'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    #url(r'^restaurants/$', RestaurantListView.as_view(), name='restaurants'),
    # url(r'^restaurants/create/$', restaurant_createview),
    #url(r'^restaurants/create/$', RestaurantCreateView.as_view(), name='restaurants-create'),
    #url(r'^restaurants/(?P<slug>[\w-]+)/$', RestaurantDetailView.as_view(), name='restaurant-detail'),
    # url(r'^restaurants/(?P<slug>\w+)/$', RestaurantListView.as_view()),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name="contact.html"), name='contact'),
]

menus/urls.py
from django.conf.urls import url, include


from django.contrib.auth.views import LoginView


from .views import (
    ItemListView,
    ItemCreateView,
    ItemDetailView,
    ItemUpdateView
)

urlpatterns = [
    url(r'^$', ItemListView.as_view(), name='list'),
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
]

menus/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from restaurants.models import RestaurantLocation


# Create your models here.
class Item(models.Model):
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant      = models.ForeignKey(RestaurantLocation)
    # Item stuff
    name            = models.CharField(max_length=120)
    contents        = models.TextField(help_text='separate each item by comma')
    excludes        = models.TextField(blank=True, null=True, help_text='separate each item by comma')
    public          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('menus:detail', kwargs={'pk': self.pk})
        # namespace: name -> restaurants:detail

    class Meta:
        ordering = ['-updated', '-timestamp'] # Item.objects.all() will display the most updated timestamp first

    # getter methods
    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

    def __str__(self):
        return self.name

menus/forms.py
from django import forms
from restaurants.models import RestaurantLocation
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public',
        ]

    # filter the restaurant list to specific user
    def __init__(self, user=None, *args, **kwargs):
        print(user) # prints the user to the console
        print(kwargs)
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)

menus/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Item
from .forms import ItemForm
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class ItemListView(ListView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemDetailView(DetailView):
    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)


class ItemCreateView(LoginRequiredMixin, CreateView):
    template_name = 'form.html'
    form_class = ItemForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        return super(ItemCreateView, self).form_valid(form)

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_form_kwargs(self):
        kwargs = super(ItemCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        # kwargs['instance'] = Item.objects.filter(user=self.request.user).first()
        return kwargs

    def get_context_data(self,*args, **kwargs):
        context = super(ItemCreateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Create Item'
        return context


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'menus/detail-update.html'
    form_class = ItemForm

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    def get_context_data(self,*args, **kwargs):
        context = super(ItemUpdateView, self).get_context_data(*args, **kwargs)
        context['title'] = 'Update Item'
        return context

    def get_form_kwargs(self):
        kwargs = super(ItemUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

menus/templates/menus/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instane.name }} | Menu Items | {{ block.super}}{% endblock head_title %}

{% block content %}
<h1>{{ form.instance.name }}</h1>
<p>Location: {{ form.instance.restaurant.name }}</p>
{% if form.instance.contents %}
Contents
<ul>
    {%  for item in form.instance.get_contents %}
        <li>{{ item }}</li>
        {% endfor %}
</ul>
{% endif %}

{% if form.instance.excludes %}
Excludes
<ul>
    {%  for item in form.instance.get_excludes %}
        <li>{{ item }}</li>
        {% endfor %}
</ul>
{% endif %}

<hr/>
<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}
{% endblock %}

menus/templates/menus/item_detail.html
{% extends "base.html" %}

{% block head_title %}Menu Items | {{ block.super}}{% endblock head_title %}

{% block content %}
<h1>{{ object.name }}</h1>
<p>Location: {{ object.restaurant.name }}</p>
{% if object.contents %}
Contents
<ul>
    {%  for item in object.get_contents %}
        <li>{{ item }}</li>
        {% endfor %}
</ul>
{% endif %}

{% if object.excludes %}
Excludes
<ul>
    {%  for item in object.get_excludes %}
        <li>{{ item }}</li>
        {% endfor %}
</ul>
{% endif %}
{% endblock %}

menus/templates/menus/item_list.html
{% extends "base.html" %}

{% block head_title %}Menu Items | {{ block.super}}{% endblock head_title %}

{% block content %}
<h1>Menu List <small><a href="{% url "menus:create" %}">Add</a></small></h1>

<ul>
{% for obj in object_list %}
    <li><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a><br/>
        {% if obj.contents %}
        Contents
        <ul>
            {%  for item in obj.get_contents %}
                <li>{{ item }}</li>
                {% endfor %}
        </ul>
        {% endif %}

        {% if obj.excludes %}
        Excludes
        <ul>
            {%  for item in obj.get_excludes %}
                <li>{{ item }}</li>
                {% endfor %}
        </ul>
        {% endif %}
    </li>
    {% empty %}
    <li><a href="{% url "menus:create" %}">Add Menu Item</a></li>
{% endfor %}
</ul>
{% endblock %}